### ISSUE TITLE
Add support for detecting folder structure in the creative

### ISSUE THREAD

**Issue by OleSan** [gardr/validator#39]
This relates to a new point in the HTML spec. [Point 5, Banner delivery](https://github.com/inma-no/advertsspec/blob/master/specification.md#5-banner-delivery). 

It should detect if the zip-file has a folder structure for the assests or not, and give an error if it does.

**Comment by sveisvei** [comment]
Should it generate a warning or an error?
Should it only generate given error/warning when testing via zip-upload?

**Comment by OleSan** [comment]
Good questions!

It should be an error, as uploading it to say AdTech will break it if it includes folders. So it is pretty critical. 

The validation should probably only be for zip-files, but I'll double check that with some people from AdOps first what they think.

**Comment by OleSan** [comment]
AdOps say we can start with only checking on zip uploads.

**Comment by sveisvei** [comment]
This will have to be done on the web-app/validator-web that processes the zip.

**Comment by sveisvei** [comment]
https://github.com/gardr/validator-web/commit/901f244d4521e3a157bb88c626c9dbb9b0eef86e
