### ISSUE TITLE
Detect cookie dropping from creatives

### ISSUE THREAD

**Issue by OleSan** [gardr/validator#41]
It would be nice if the validator also checked for cookie dropping by the creatives. It should give an error be default, but be tweaked in site config if they don't want errors on it.

**Comment by sveisvei** [comment]
cookie dropping?

**Comment by OleSan** [comment]
Setting cookies :) They shouldn't set cookies.

**Comment by sveisvei** [comment]
Most tracking does, are you thinking not setting cookies on serving domain - only setting on 3.rd party?

**Comment by OleSan** [comment]
Checked a bit more with people concerned about data leakage. 

It would be nice with just a version 1.0 where it lists up the cookies set (1st and 3rd party). And in the longer run look at a white-list and black-list. Where those in the blacklist will give errors, white-list ignored. 

Is that possible? Could perhaps just be in the validator under "Information about this run" first.

**Comment by sveisvei** [comment]
Sure, its no issue to collect what is there at end of the run at least.
