### ISSUE TITLE
HTTPS - Detect if the creatives use https or not

### ISSUE THREAD

**Issue by OleSan** [gardr/validator#42]
Should perhaps be off as default, but configurable in each site config with something like secure: true

When set as true, it should give error if there are any references with http as protocol, as they will eventually fail to load when we turn on https on our sites. 

Long run should also do some TLS-checks, but that is perhaps more complicated. The most important for AdOps now is to detect if there are any http-references in the creative.

**Comment by sveisvei** [comment]
https://github.com/gardr/validator/commit/4dd94f6617355b427d7c1a9c12d606010ef31042
Changed to on by default. Was optional as a warning before.

**Comment by OleSan** [comment]
Will this test as it is now fail if it calls on a http-resource? Seems like it only checks the server for TLS support?

**Comment by sveisvei** [comment]
what do you mean if "calls on"? Link goes to non-https? or any resource linked is not https-able?

**Comment by OleSan** [comment]
Any link goes to non https. 

So anything with src="http://example.com" or similar would fail.

**Comment by sveisvei** [comment]
Aha, and this should generate only a warning? An error would be abit to much maybe. 
The most important thing is that the content and the server serving the content supports https, not necessarily the link target?

**Comment by OleSan** [comment]
I'm thinking like this:

Everything that the browser will warn about should give an error. So that when sites move to https, we won't have banner ads that give warnings in browsers. 

I'm pretty sure script will be blocked and give a warnings, not sure about image tags and image urls in CSS though.

**Comment by sveisvei** [comment]
https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md

**Comment by sveisvei** [comment]
@OleSan which formats should have this activated?

**Comment by sveisvei** [comment]
Did some initial testing with ssl labs here: https://github.com/gardr/validator/tree/ssllabs

**Comment by OleSan** [comment]
@sveisvei On all formats in Schibsted/VG/Storby at least. The other sites can add it in their config if they want to.
