### ISSUE TITLE
Whitelist GSAP if its from the right CDN

### ISSUE THREAD

**Issue by OleSan** [gardr/validator#43]
We have this in the spec now:

Use of GSAP with the cloudflare CDN won't count against total ad size.
`<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js"></script>`

We should whitelist that in our validator as well.

**Comment by sveisvei** [comment]
Intend to allow all GSAP code, or just `TweenLight` and `TweenMax`? Should we also enforce latest versions here as well?

**Comment by sveisvei** [comment]
https://github.com/gardr/validator/commit/1bd0ba5bb9deed259f1d9477886005e207193528
