### ISSUE TITLE
Wrong jQuery version

### ISSUE THREAD

**Issue by henlarsen** [gardr/validator#48]
![image](https://cloud.githubusercontent.com/assets/8911144/13743902/d47fa852-e9e4-11e5-96db-8b4da0cb80dd.png)

Gardr validator asks for jQuery version v1.12.1, this is not an available vesion from Google CDN, it should be v1.12.0 i think.

**Comment by sveisvei** [comment]
This is based on the released tags from jQuery github repo, so there might at some times be incorrect because there is a lag from release until they are available from CDNs etc.
